on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: "Make install"
        run: make install
      - name: "Make compile"
        run: make compile
      - name: "Make test"
        run: make test
